version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: hypbox
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm i
      - run:
          name: Running Tests
          command: npm run test
          # command: npm run test:cov
          # command: npm run test:badges
  deploy_on_app_engine:
    docker:
      - image: google/cloud-sdk:slim
        auth:
          username: hypbox
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Installing Nodejs and NPM
          command: |
            apt install -y nodejs npm
      - run:
          name: Installing Dependencies
          command: npm i
      - run:
          name: Building
          command: npm run build
      - run:
          name: Deploying to App Engine
          command: |
            echo ${GCLOUD_SERVICE_KEY} > /tmp/sa_key.json
            gcloud auth activate-service-account --key-file=/tmp/sa_key.json
            rm /tmp/sa_key.json
            gcloud config set project falcon-314920
            gcloud config set compute/region us-central
            gcloud app deploy
workflows:
  version: 2
  build_test_workflow:
    jobs:
      - test
      - deploy_on_app_engine:
          filters:
            branches:
              only:
                - main-change-this-later
          requires:
            - test
