version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: hypbox
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm i
      - run:
          name: Running Tests
          command: npm t
  deploy_to_staging:
    docker:
      # - image: cimg/node:14.10.1
      - image: google/cloud-sdk:slim
        auth:
          username: hypbox
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Installing Node
          command: apt install -y nodejs
      - run:
          name: Deploying to App Engine
          command: |
            echo ${GCLOUD_SERVICE_KEY} > /tmp/sa_key.json
            gcloud auth activate-service-account --key-file=/tmp/sa_key.json
            rm /tmp/sa_key.json
            gcloud config set project falcon-314920
            gcloud config set compute/region us-central
            ls
            gcloud app deploy

workflows:
  version: 2
  build_test_workflow:
    jobs:
      - build_test
      - deploy_to_staging:
          filters:
            branches:
              only:
                - main
          requires:
            - build_test
