version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: hypbox
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm i
      - run:
          name: Running Tests
          command: npm t
  build_deploy_to_staging:
    docker:
      # - image: cimg/node:14.10.1
      - image: google/cloud-sdk:slim
        auth:
          username: hypbox
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Installing Nodejs
          command: echo 0 && apt install -y nodejs
      - run:
          name: Building
          command: echo 1 && npm run build
      - run:
          name: Deploying to App Engine
          command: |
            echo 2
            echo ${GCLOUD_SERVICE_KEY} > /tmp/sa_key.json
            gcloud auth activate-service-account --key-file=/tmp/sa_key.json
            rm /tmp/sa_key.json
            gcloud config set project falcon-314920
            gcloud config set compute/region us-central
            gcloud app deploy --log-http --verbosity=debug
workflows:
  version: 2
  build_test_workflow:
    jobs:
      - test
      - build_deploy_to_staging:
          filters:
            branches:
              only:
                - main
          requires:
            - test
